// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Roster.Platform.Data;

#nullable disable

namespace Roster.Platform.Migrations
{
    [DbContext(typeof(RosterDb))]
    [Migration("20261002143834_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Roster.Platform.Data.AgentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_name");

                    b.Property<string>("Archetype")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("archetype");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<string>("SkillsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("skills_json");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("VersionLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_label");

                    b.HasKey("Id")
                        .HasName("pk_agent_versions");

                    b.HasIndex("AgentName", "Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_versions_agent_name_hash");

                    b.ToTable("agent_versions", (string)null);
                });

            modelBuilder.Entity("Roster.Platform.Data.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DefaultEndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_endpoint_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("DefaultEndpointId")
                        .HasDatabaseName("ix_users_default_endpoint_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Roster.Platform.Data.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CancelRequested")
                        .HasColumnType("boolean")
                        .HasColumnName("cancel_requested");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("endpoint_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("OverridesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("overrides_json");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scenario");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assignments");

                    b.HasIndex("EndpointId")
                        .HasDatabaseName("ix_assignments_endpoint_id");

                    b.HasIndex("OwnerId", "CreatedAt")
                        .HasDatabaseName("ix_assignments_owner_id_created_at");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("Roster.Platform.Data.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_hash");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_name");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedById")
                        .HasColumnType("text")
                        .HasColumnName("decided_by_id");

                    b.Property<string>("DecidedByName")
                        .HasColumnType("text")
                        .HasColumnName("decided_by_name");

                    b.Property<string>("DecidedByTitle")
                        .HasColumnType("text")
                        .HasColumnName("decided_by_title");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("decision");

                    b.Property<string>("DecisionReason")
                        .HasColumnType("text")
                        .HasColumnName("decision_reason");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("FilePath")
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<Guid>("InvocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invocation_id");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recommendation");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_findings");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_findings_assignment_id");

                    b.HasIndex("InvocationId")
                        .HasDatabaseName("ix_findings_invocation_id");

                    b.ToTable("findings", (string)null);
                });

            modelBuilder.Entity("Roster.Platform.Data.Invocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_hash");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_name");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<Guid?>("EndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("endpoint_id");

                    b.Property<string>("EndpointName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint_name");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("InputText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_text");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("OutputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_json");

                    b.Property<string>("OutputStrategy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("output_strategy");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<string>("PhaseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phase_key");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("Reasoning")
                        .HasColumnType("text")
                        .HasColumnName("reasoning");

                    b.Property<string>("RuntimeKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("runtime_kind");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("StepKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("step_key");

                    b.Property<string>("ToolCallsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("tool_calls_json");

                    b.Property<string>("TraceId")
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_invocations");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_invocations_assignment_id");

                    b.HasIndex("AgentName", "AgentHash")
                        .HasDatabaseName("ix_invocations_agent_name_agent_hash");

                    b.ToTable("invocations", (string)null);
                });

            modelBuilder.Entity("Roster.Platform.Data.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<string>("LockedBy")
                        .HasColumnType("text")
                        .HasColumnName("locked_by");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<DateTimeOffset>("NotBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("Pool")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pool");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("TraceParent")
                        .HasColumnType("text")
                        .HasColumnName("trace_parent");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_jobs_idempotency_key");

                    b.HasIndex("Pool", "State", "NotBefore")
                        .HasDatabaseName("ix_jobs_pool_state_not_before");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("Roster.Platform.Data.ModelEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("text")
                        .HasColumnName("base_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<string>("DefaultModel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_model");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int>("MaxConcurrency")
                        .HasColumnType("integer")
                        .HasColumnName("max_concurrency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("NativeStructuredOutput")
                        .HasColumnType("boolean")
                        .HasColumnName("native_structured_output");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<bool>("ReasoningModel")
                        .HasColumnType("boolean")
                        .HasColumnName("reasoning_model");

                    b.Property<int?>("RequestsPerMinute")
                        .HasColumnType("integer")
                        .HasColumnName("requests_per_minute");

                    b.Property<bool>("SupportsStreaming")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_streaming");

                    b.Property<bool>("SupportsTools")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_tools");

                    b.Property<string>("TierModelsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tier_models_json");

                    b.HasKey("Id")
                        .HasName("pk_endpoints");

                    b.HasIndex("CredentialId")
                        .HasDatabaseName("ix_endpoints_credential_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_endpoints_owner_id");

                    b.ToTable("endpoints", (string)null);
                });

            modelBuilder.Entity("Roster.Platform.Data.Phase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("OutputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_json");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_phases");

                    b.HasIndex("AssignmentId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_phases_assignment_id_order");

                    b.ToTable("phases", (string)null);
                });

            modelBuilder.Entity("Roster.Platform.Data.RetroCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentHash")
                        .HasColumnType("text")
                        .HasColumnName("agent_hash");

                    b.Property<string>("AgentName")
                        .HasColumnType("text")
                        .HasColumnName("agent_name");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<string>("AssistedBy")
                        .HasColumnType("text")
                        .HasColumnName("assisted_by");

                    b.Property<string>("AuthorId")
                        .HasColumnType("text")
                        .HasColumnName("author_id");

                    b.Property<string>("AuthorName")
                        .HasColumnType("text")
                        .HasColumnName("author_name");

                    b.Property<string>("AuthorTitle")
                        .HasColumnType("text")
                        .HasColumnName("author_title");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sentiment");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_retro_cards");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_retro_cards_assignment_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_retro_cards_session_id");

                    b.HasIndex("AgentName", "AgentHash")
                        .HasDatabaseName("ix_retro_cards_agent_name_agent_hash");

                    b.ToTable("retro_cards", (string)null);
                });

            modelBuilder.Entity("Roster.Platform.Data.RetroMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("InProgress")
                        .HasColumnType("boolean")
                        .HasColumnName("in_progress");

                    b.Property<Guid?>("InvocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invocation_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_retro_messages");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_retro_messages_session_id_sequence");

                    b.ToTable("retro_messages", (string)null);
                });

            modelBuilder.Entity("Roster.Platform.Data.RetroSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_retro_sessions");

                    b.HasIndex("AssignmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_retro_sessions_assignment_id");

                    b.ToTable("retro_sessions", (string)null);
                });

            modelBuilder.Entity("Roster.Platform.Data.RunEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.HasKey("Id")
                        .HasName("pk_run_events");

                    b.HasIndex("AssignmentId", "Id")
                        .HasDatabaseName("ix_run_events_assignment_id_id");

                    b.ToTable("run_events", (string)null);
                });

            modelBuilder.Entity("Roster.Platform.Data.UserCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<byte[]>("Sealed")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sealed");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_credentials");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_credentials_user_id");

                    b.ToTable("credentials", (string)null);
                });

            modelBuilder.Entity("Roster.Platform.Data.AppUser", b =>
                {
                    b.HasOne("Roster.Platform.Data.ModelEndpoint", null)
                        .WithMany()
                        .HasForeignKey("DefaultEndpointId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_endpoints_default_endpoint_id");
                });

            modelBuilder.Entity("Roster.Platform.Data.Assignment", b =>
                {
                    b.HasOne("Roster.Platform.Data.ModelEndpoint", null)
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_assignments_endpoints_endpoint_id");

                    b.HasOne("Roster.Platform.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_users_owner_id");
                });

            modelBuilder.Entity("Roster.Platform.Data.Finding", b =>
                {
                    b.HasOne("Roster.Platform.Data.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_findings_assignments_assignment_id");

                    b.HasOne("Roster.Platform.Data.Invocation", null)
                        .WithMany()
                        .HasForeignKey("InvocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_findings_invocations_invocation_id");
                });

            modelBuilder.Entity("Roster.Platform.Data.Invocation", b =>
                {
                    b.HasOne("Roster.Platform.Data.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invocations_assignments_assignment_id");
                });

            modelBuilder.Entity("Roster.Platform.Data.ModelEndpoint", b =>
                {
                    b.HasOne("Roster.Platform.Data.UserCredential", null)
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_endpoints_credentials_credential_id");

                    b.HasOne("Roster.Platform.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_endpoints_users_owner_id");
                });

            modelBuilder.Entity("Roster.Platform.Data.Phase", b =>
                {
                    b.HasOne("Roster.Platform.Data.Assignment", null)
                        .WithMany("Phases")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_phases_assignments_assignment_id");
                });

            modelBuilder.Entity("Roster.Platform.Data.RetroCard", b =>
                {
                    b.HasOne("Roster.Platform.Data.RetroSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retro_cards_retro_sessions_session_id");
                });

            modelBuilder.Entity("Roster.Platform.Data.RetroMessage", b =>
                {
                    b.HasOne("Roster.Platform.Data.RetroSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retro_messages_retro_sessions_session_id");
                });

            modelBuilder.Entity("Roster.Platform.Data.RetroSession", b =>
                {
                    b.HasOne("Roster.Platform.Data.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retro_sessions_assignments_assignment_id");
                });

            modelBuilder.Entity("Roster.Platform.Data.RunEvent", b =>
                {
                    b.HasOne("Roster.Platform.Data.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_events_assignments_assignment_id");
                });

            modelBuilder.Entity("Roster.Platform.Data.UserCredential", b =>
                {
                    b.HasOne("Roster.Platform.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credentials_users_user_id");
                });

            modelBuilder.Entity("Roster.Platform.Data.Assignment", b =>
                {
                    b.Navigation("Phases");
                });
#pragma warning restore 612, 618
        }
    }
}
