using System.Diagnostics;
using Microsoft.Extensions.Options;
using SdlcStudio.Api.Options;

namespace SdlcStudio.Api.Tools;

/// <summary>
/// A local git repository per workflow run (workspace/&lt;run&gt;/repo). The develop phase writes each
/// approved task as one small commit on a story branch; a story branch is the "merge request checkpoint".
/// </summary>
/// <remarks>
/// <para>
/// WHY shell out to the git CLI? It is installed on every developer machine, behaves exactly like the
/// commands a human would run, and needs no extra package. ALTERNATIVE: LibGit2Sharp (in-process,
/// no git install needed, but a native dependency and a different mental model), or the GitHub REST
/// API / Octokit to commit straight to a remote without a local clone.
/// </para>
/// <para>
/// If git is not installed (or Studio:Git:Enabled is false) the workspace still gets the files and we
/// record pseudo commit ids, so the sample never fails just because git is missing.
/// </para>
/// </remarks>
public sealed class GitWorkspace(IOptions<StudioOptions> options, ILogger<GitWorkspace> logger)
{
    private readonly GitOptions _git = options.Value.Git;

    public const string MainBranch = "main";

    public async Task EnsureRepositoryAsync(string repoPath, CancellationToken ct)
    {
        Directory.CreateDirectory(repoPath);
        if (!_git.Enabled || Directory.Exists(Path.Combine(repoPath, ".git"))) return;

        await File.WriteAllTextAsync(Path.Combine(repoPath, "README.md"),
            "# Generated by SDLC Studio\n\nEach commit was written by the developer agent and approved by the code reviewer agent.\n", ct);

        if (await TryGitAsync(repoPath, ct, "init", "-b", MainBranch) is null) return;
        await TryGitAsync(repoPath, ct, "add", "-A");
        await TryGitAsync(repoPath, ct, "commit", "-m", "chore: initial commit");
    }

    /// <summary>Creates (or switches to) the story branch, starting from main.</summary>
    public Task CheckoutStoryBranchAsync(string repoPath, string branch, CancellationToken ct) =>
        TryGitAsync(repoPath, ct, "checkout", "-B", branch, MainBranch);

    /// <summary>Writes files and commits them. Returns the commit sha (or a pseudo id without git).</summary>
    public async Task<string> CommitAsync(string repoPath, IEnumerable<(string Path, string Content)> files, string message, CancellationToken ct)
    {
        var root = Path.GetFullPath(repoPath);
        foreach (var (relative, content) in files)
        {
            // Model output decides these paths, so treat them as untrusted input.
            var full = Path.GetFullPath(Path.Combine(root, relative));
            if (!full.StartsWith(root, StringComparison.OrdinalIgnoreCase) || full.Contains($"{Path.DirectorySeparatorChar}.git"))
                throw new InvalidOperationException($"Refusing to write outside the repository: {relative}");

            Directory.CreateDirectory(Path.GetDirectoryName(full)!);
            await File.WriteAllTextAsync(full, content, ct);
        }

        await TryGitAsync(repoPath, ct, "add", "-A");
        await TryGitAsync(repoPath, ct, "commit", "--allow-empty", "-m", message);
        return (await TryGitAsync(repoPath, ct, "rev-parse", "--short", "HEAD"))?.Trim()
            ?? Guid.NewGuid().ToString("N")[..7];
    }

    /// <summary>Simulates merging an approved MR: merge the story branch into main.</summary>
    public async Task MergeAsync(string repoPath, string branch, CancellationToken ct)
    {
        await TryGitAsync(repoPath, ct, "checkout", MainBranch);
        await TryGitAsync(repoPath, ct, "merge", "--no-ff", "-m", $"Merge branch '{branch}'", branch);
    }

    public async Task<string> DiffStatAsync(string repoPath, string branch, CancellationToken ct) =>
        await TryGitAsync(repoPath, ct, "diff", "--stat", $"{MainBranch}...{branch}") ?? "(git not available)";

    private async Task<string?> TryGitAsync(string repoPath, CancellationToken ct, params string[] args)
    {
        if (!_git.Enabled) return null;
        try
        {
            var psi = new ProcessStartInfo("git")
            {
                WorkingDirectory = repoPath,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
            };
            // Identity is passed per command so we never touch the user's global git config.
            foreach (var a in (string[])["-c", $"user.name={_git.AuthorName}", "-c", $"user.email={_git.AuthorEmail}", .. args])
                psi.ArgumentList.Add(a);

            using var process = Process.Start(psi)!;
            var stdout = await process.StandardOutput.ReadToEndAsync(ct);
            var stderr = await process.StandardError.ReadToEndAsync(ct);
            await process.WaitForExitAsync(ct);

            if (process.ExitCode != 0)
            {
                logger.LogWarning("git {Args} failed: {Error}", string.Join(' ', args), stderr.Trim());
                return null;
            }
            return stdout;
        }
        catch (Exception ex) when (ex is System.ComponentModel.Win32Exception or InvalidOperationException)
        {
            logger.LogWarning("git is not available ({Message}); continuing without version control.", ex.Message);
            return null;
        }
    }
}
