using Microsoft.Extensions.Options;
using SdlcStudio.Api.Options;

namespace SdlcStudio.Api.Tools;

/// <summary>
/// Produces a merge request "checkpoint" for a story branch. In this sample it does not call GitHub;
/// it writes the exact instructions a developer would run to push the branch and open the PR.
/// </summary>
/// <remarks>
/// WHY mocked: opening real PRs from a sample would need a token with write access to a repository.
/// To make it real, pick one:
/// <list type="bullet">
/// <item>GitHub MCP server: see <see cref="GitHubMcpTools"/> for the (commented out) MCP client code, then
/// call its <c>create_pull_request</c> tool from code, or hand the tools to an agent.</item>
/// <item>Octokit.NET or the GitHub REST API: <c>POST /repos/{owner}/{repo}/pulls</c>.</item>
/// <item>Process.Start("gh", "pr create ...") using the GitHub CLI's existing login.</item>
/// </list>
/// </remarks>
public sealed class MergeRequestPublisher(IOptions<StudioOptions> options)
{
    public string BuildInstructions(string repoPath, string branch, string storyKey, string storyTitle, IEnumerable<string> commits, string diffStat) => $"""
        # Merge request checkpoint: {storyKey} {storyTitle}

        The developer agent finished every task for this story on branch `{branch}`.
        Review the commits below, then approve this checkpoint in the studio (or reject it with a reason
        and the story is re-developed with your feedback).

        ## Commits
        {string.Join("\n", commits.Select(c => $"- {c}"))}

        ## Diff summary
        ```
        {diffStat.Trim()}
        ```

        ## To publish this for real
        ```bash
        cd "{Path.GetFullPath(repoPath)}"
        git remote add origin {options.Value.Git.Remote}   # once
        git push -u origin {branch}
        gh pr create --base {GitWorkspace.MainBranch} --head {branch} \
          --title "{storyKey}: {storyTitle}" \
          --body "Implements {storyKey}. Generated by SDLC Studio; every commit passed the code-review agent."
        ```
        """;
}
