using System.Text.Json;
using IncidentTriage.Ai;
using IncidentTriage.Persistence;
using IncidentTriage.Tools;
using Microsoft.Agents.AI.Workflows;

namespace IncidentTriage.Workflow.Executors;

/// <summary>
/// Step 6 (no LLM + a human): join the two writer branches, save everything locally, ask for approval,
/// then create the Jira issues and Confluence pages with plain API calls.
/// </summary>
/// <remarks>
/// <para><b>Fan-in.</b> The barrier edge delivers <see cref="JiraDrafts"/> and <see cref="PostmortemDrafts"/>
/// as two separate messages in the same superstep, so this executor collects them and acts when both are in.
/// ALTERNATIVE: <c>AggregatingExecutor&lt;TIn, TAcc&gt;</c> or a <c>BindAsExecutor</c> aggregator function,
/// which work well when every input has the same type.</para>
/// <para><b>Why a second human gate?</b> Root-cause review is about <i>correctness</i>; this one is about
/// <i>side effects</i>: tickets and wiki pages that notify people. Different question, different moment.</para>
/// <para><b>Output.</b> <c>YieldOutputAsync</c> produces the workflow's result (a <c>WorkflowOutputEvent</c>
/// for the host). This executor is registered with <c>WithOutputFrom</c> in the builder.</para>
/// </remarks>
public sealed class PublishExecutor(JiraClient jira, ConfluenceClient confluence, TriageJournal journal) : Executor("publish")
{
    private JiraDrafts? _jira;
    private PostmortemDrafts? _pages;

    protected override ProtocolBuilder ConfigureProtocol(ProtocolBuilder protocolBuilder) =>
        protocolBuilder
            .SendsMessage<PublishApprovalRequest>()
            .YieldsOutput<TriageReport>()
            .ConfigureRoutes(routes => routes
                .AddHandler<JiraDrafts>((drafts, ctx, ct) => { _jira = drafts; return TryRequestApprovalAsync(ctx, ct); })
                .AddHandler<PostmortemDrafts>((pages, ctx, ct) => { _pages = pages; return TryRequestApprovalAsync(ctx, ct); })
                .AddHandler<PublishDecision>(OnDecisionAsync));

    private async ValueTask TryRequestApprovalAsync(IWorkflowContext context, CancellationToken ct)
    {
        if (_jira is null || _pages is null) return; // wait for the other branch

        // Always keep a local copy first: approval or not, the drafts are useful and auditable.
        foreach (var issue in _jira.Issues)
            journal.WriteArtifact($"jira-{issue.ClusterId}.json", JsonSerializer.Serialize(issue, JsonDefaults.Options));
        foreach (var page in _pages.Pages)
            journal.WriteArtifact($"postmortem-{page.ClusterId}.md", page.Markdown);

        if (_jira.Issues.Count == 0)
        {
            await FinishAsync(published: false, [], [], context, ct);
            return;
        }

        await context.ReportAsync(Id, $"Drafts saved to {journal.Folder}. Waiting for publish approval.", ct);
        await context.SendMessageAsync(new PublishApprovalRequest(_jira.Issues, _pages.Pages, journal.Folder), ct);
    }

    private async ValueTask OnDecisionAsync(PublishDecision decision, IWorkflowContext context, CancellationToken ct)
    {
        journal.Record(JournalKind.HumanDecision, decision.Reviewer, "publish", new { decision.Approved }, decision.Reason);
        if (!decision.Approved)
        {
            await context.ReportAsync(Id, "Publishing declined. Drafts stay local.", ct);
            await FinishAsync(published: false, [], [], context, ct);
            return;
        }

        List<string> keys = [], urls = [];
        foreach (var issue in _jira!.Issues)
        {
            var key = await jira.CreateIssueAsync(issue, ct);
            keys.Add(key);

            var page = _pages!.Pages.FirstOrDefault(p => p.ClusterId == issue.ClusterId);
            if (page is not null)
            {
                var url = await confluence.CreatePageAsync($"{page.Title} ({key})", page.Markdown, ct);
                urls.Add(url);
                // "Update the ticket with the work": link the postmortem back to the issue.
                await jira.AddCommentAsync(key, $"Postmortem draft: {url}\nGenerated by the incident-triage workflow, run {journal.RunId}.", ct);
            }

            journal.Record(JournalKind.Published, Id, issue.ClusterId, new { IssueKey = key, PageUrl = urls.LastOrDefault() });
            await context.ReportAsync(Id, $"{issue.ClusterId}: created {key}", ct);
        }

        await FinishAsync(published: true, keys, urls, context, ct);
    }

    private async ValueTask FinishAsync(bool published, List<string> keys, List<string> urls, IWorkflowContext context, CancellationToken ct)
    {
        var analysis = _jira?.Analysis;
        var report = new TriageReport(journal.RunId, journal.Folder, analysis?.Incidents ?? [], keys, urls, published);
        journal.Record(JournalKind.RunCompleted, Id, null, new { published, keys, urls });
        await context.YieldOutputAsync(report, ct);
    }
}
