using IncidentTriage.Agents;
using IncidentTriage.Persistence;
using IncidentTriage.Rag;
using IncidentTriage.Repo;
using IncidentTriage.Tools;
using IncidentTriage.Workflow.Executors;
using Microsoft.Agents.AI.Workflows;

namespace IncidentTriage.Workflow;

/// <summary>
/// Wires the executors into a graph.
/// </summary>
/// <remarks>
/// <code>
///  TriageRequest
///      │
///  [ingest] ──► [extract-signals] ──► [correlate] ──► [root-cause] ◄──► (port: root-cause-review) ◄─► human
///                                                          │ TriageAnalysis
///                                              ┌───────────┴───────────┐   fan-out (parallel)
///                                         [jira-draft]          [postmortem-draft]
///                                              └───────────┬───────────┘   fan-in barrier
///                                                      [publish] ◄──► (port: publish-approval) ◄─► human
///                                                          │
///                                                     TriageReport (workflow output)
/// </code>
/// <para>Run <c>dotnet run -- --mermaid</c> to print the same graph generated by <c>WorkflowVisualizer</c>.</para>
/// <para><b>Ports are "external calls".</b> <c>AddExternalCall&lt;TRequest, TResponse&gt;(source, portId)</c> adds a
/// <c>RequestPort</c> with edges in both directions: requests flow out to the host as <c>RequestInfoEvent</c>s,
/// responses flow back into <c>source</c>. A port is just another node, so the same mechanism could call a
/// different system (an approval service, a ticketing queue) instead of a person at a console.</para>
/// <para><b>Message routing.</b> Edges carry any message the source sends, and an executor only receives the types it
/// registered handlers for. So <c>root-cause</c>'s review requests reach only the port, and its
/// <see cref="TriageAnalysis"/> reaches only the two writers, even though they share outgoing edges. For explicit
/// routing use conditional edges (<c>AddEdge&lt;T&gt;(from, to, condition)</c>) or <c>AddSwitch</c>.</para>
/// </remarks>
public static class TriageWorkflow
{
    public const string RootCauseReviewPort = "root-cause-review";
    public const string PublishApprovalPort = "publish-approval";

    public static Microsoft.Agents.AI.Workflows.Workflow Build(
        AgentFactory agents, RepositoryCloner cloner, KnowledgeIndex index, JiraClient jira, ConfluenceClient confluence, TriageJournal journal, int maxReviewRounds)
    {
        // Executors are instances: Agent Framework calls them "executor bindings". ExecutorBinding has an implicit
        // conversion from Executor, which is why we can pass these objects straight to the builder.
        // ALTERNATIVE: register factories (ExecutorBindingExtensions.BindExecutor(factoryAsync)) so each run gets
        // fresh executor instances. Needed when one Workflow object serves many concurrent runs, e.g. in a web app.
        var ingest = new IngestExecutor(cloner, index, journal);
        var extract = new SignalExtractionExecutor(agents.CreateSignalExtractor(), journal);
        var correlate = new CorrelationExecutor(agents.CreateIncidentCorrelator(), journal);
        var rootCause = new RootCauseExecutor(ctx => agents.CreateRootCauseAnalyst(ctx.Snapshot), journal, maxReviewRounds);
        var jiraDraft = new JiraDraftExecutor(agents.CreateJiraDrafter(), journal);
        var postmortem = new PostmortemExecutor(agents.CreatePostmortemWriter(), journal);
        var publish = new PublishExecutor(jira, confluence, journal);

        return new WorkflowBuilder(ingest)
            .WithName("incident-triage")
            .WithDescription("Reports + repo -> signals -> clusters -> reviewed root cause -> Jira + Confluence drafts -> approved publish")
            .AddEdge(ingest, extract)
            .AddEdge(extract, correlate)
            .AddEdge(correlate, rootCause)
            .AddExternalCall<RootCauseReviewRequest, ReviewDecision>(rootCause, RootCauseReviewPort)
            .AddFanOutEdge(rootCause, [jiraDraft, postmortem])
            .AddFanInBarrierEdge([jiraDraft, postmortem], publish)
            .AddExternalCall<PublishApprovalRequest, PublishDecision>(publish, PublishApprovalPort)
            .WithOutputFrom(publish)
            .Build();
    }
}
